// ============================================================
// Dominion Estates — Reviews publisher
// Regenerates the static reviews section (cards + SEO schema) in
// index.html from reviews.json, the committed source of truth for
// what's currently published. The live site never reads Firestore for
// reviews — Firestore is only the intake/moderation queue guests write
// to and admins moderate (see checkin-admin/reviews/). Approving a
// review there does NOT change the site; running this script does.
//
// Usage: node reviews/build.mjs
// Reads:  reviews.json
// Writes: index.html (only the two regions below)
// ============================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const indexPath = join(repoRoot, 'index.html');
const reviews = JSON.parse(readFileSync(join(repoRoot, 'reviews.json'), 'utf8'));

const esc = (s = '') =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// ── Guest-facing cards (between <!-- REVIEWS:START/END --> in the HTML body) ──
function renderCards(list) {
  return list
    .map((r) => {
      const initial = esc((r.name || '?').trim().charAt(0).toUpperCase());
      const stars = '★'.repeat(Math.max(0, Math.min(5, r.rating ?? 5)));
      return `        <div class="review-card-hp">
          <div class="review-card-head">
            <div class="review-avatar-hp">${initial}</div>
            <div>
              <div class="review-name-hp">${esc(r.name)}</div>
              <div class="review-date-hp">${esc(r.date)}</div>
            </div>
            <div class="review-stars-hp">${stars}</div>
          </div>
          <p class="review-text-hp">${esc(r.text)}</p>
        </div>`;
    })
    .join('\n\n');
}

function spliceBetweenMarkers(html, startMarker, endMarker, innerContent) {
  const startIdx = html.indexOf(startMarker);
  const endIdx = html.indexOf(endMarker, startIdx);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`Could not find markers "${startMarker.trim()}" / "${endMarker.trim()}" in index.html`);
  }
  const contentStart = startIdx + startMarker.length;
  return html.slice(0, contentStart) + '\n' + innerContent + '\n        ' + html.slice(endIdx);
}

// ── SEO schema (aggregateRating + review array inside the JSON-LD block) ──
function renderSchema(list) {
  const count = list.length;
  const entries = list
    .map(
      (r) => `      {
        "@type": "Review",
        "author": {"@type": "Person", "name": ${JSON.stringify(r.name)}},
        "datePublished": ${JSON.stringify(r.dateISO)},
        "reviewRating": {"@type": "Rating", "ratingValue": ${JSON.stringify(String(r.rating))}},
        "reviewBody": ${JSON.stringify(r.text)}
      }`
    )
    .join(',\n');

  return `"aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "5",
      "bestRating": "5",
      "ratingCount": ${JSON.stringify(String(count))},
      "reviewCount": ${JSON.stringify(String(count))}
    },
    "review": [
${entries}
    ],`;
}

function spliceJsonLd(html, newBlock) {
  const startNeedle = '"aggregateRating": {';
  const endNeedle = '\n    "sameAs": [';
  const startIdx = html.indexOf(startNeedle);
  const endIdx = html.indexOf(endNeedle, startIdx);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error('Could not find the aggregateRating/review JSON-LD block in index.html');
  }
  return html.slice(0, startIdx) + newBlock + html.slice(endIdx);
}

// ── Build ──────────────────────────────────────────────────
let html = readFileSync(indexPath, 'utf8');

html = spliceBetweenMarkers(
  html,
  '<!-- REVIEWS:START (auto-generated by reviews/build.mjs from reviews.json — do not hand-edit) -->',
  '<!-- REVIEWS:END -->',
  renderCards(reviews)
);
html = spliceJsonLd(html, renderSchema(reviews));

writeFileSync(indexPath, html, 'utf8');
console.log(`✓ Regenerated reviews section in index.html from ${reviews.length} review(s) in reviews.json`);
